name: Email Scraper Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  email-scraping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scrapy validators dropbox

      # Step 4: Download file from Dropbox
      - name: Download file from Dropbox
        id: download
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        run: |
          python - <<EOF
          import dropbox
          import os

          ACCESS_TOKEN = os.getenv("DROPBOX_ACCESS_TOKEN")
          if not ACCESS_TOKEN:
              raise ValueError("Dropbox Access Token is not set.")

          dbx = dropbox.Dropbox(ACCESS_TOKEN)
          DROPBOX_FILE_PATH = "/Masatsugu Shimizu/emailcrawlerData/500.csv"
          LOCAL_FILE_PATH = "500.csv"

          try:
              with open(LOCAL_FILE_PATH, "wb") as f:
                  metadata, res = dbx.files_download(DROPBOX_FILE_PATH)
                  f.write(res.content)
              print(f"Downloaded {DROPBOX_FILE_PATH} to {LOCAL_FILE_PATH}")
          except Exception as e:
              print(f"Error downloading file: {e}")
              raise
          EOF

      # Step 5: Debugging step to check files in the directory
      - name: List files in the working directory
        run: |
          echo "Listing all files in the working directory:"
          ls -la
          echo "Checking if 500.csv exists:"
          [ -f 500.csv ] && echo "File 500.csv exists" || echo "File 500.csv does not exist"

      # Step 6: Run Email to URL Script
      - name: Run Email to URL Script
        run: python EmailToURL.py
