name: Dynamic Email Scraper Workflow

on:
  workflow_dispatch: # Allows manual trigger with custom inputs
    inputs:
      file_name:
        description: 'Name of the file to process from Dropbox'
        required: false
        default: '500.csv'  # Default file name


jobs:
  email-scraping:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scrapy validators dropbox

      # Step 4: Set up dynamic file name
      - name: Set file name
        id: set-file-name
        run: echo "FILE_NAME=${{ github.event.inputs.file_name || '500.csv' }}" >> $GITHUB_ENV

      # Step 5: Download file from Dropbox
      - name: Download file from Dropbox
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          FILE_NAME: ${{ env.FILE_NAME }}
        run: |
          python - <<EOF
          import dropbox
          import os

          ACCESS_TOKEN = os.getenv("DROPBOX_ACCESS_TOKEN")
          FILE_NAME = os.getenv("FILE_NAME")
          if not ACCESS_TOKEN:
              raise ValueError("Dropbox Access Token is not set.")
          if not FILE_NAME:
              raise ValueError("FILE_NAME environment variable is not set.")

          dbx = dropbox.Dropbox(ACCESS_TOKEN)
          DROPBOX_FILE_PATH = f"/Masatsugu Shimizu/emailcrawlerData/{FILE_NAME}"
          LOCAL_FILE_PATH = FILE_NAME

          try:
              with open(LOCAL_FILE_PATH, "wb") as f:
                  metadata, res = dbx.files_download(DROPBOX_FILE_PATH)
                  f.write(res.content)
              print(f"Downloaded {DROPBOX_FILE_PATH} to {LOCAL_FILE_PATH}")
          except Exception as e:
              print(f"Error downloading file: {e}")
              raise
          EOF

      # Step 6: Debugging step to check files in the directory
      - name: List files in the working directory
        run: |
          echo "Listing all files in the working directory:"
          ls -la
          echo "Checking if the file exists:"
          [ -f "${{ env.FILE_NAME }}" ] && echo "File ${{ env.FILE_NAME }} exists" || echo "File ${{ env.FILE_NAME }} does not exist"

      # Step 7: Run Email to URL Script with dynamic file name
      - name: Run Email to URL Script
        env:
          FILE_PATH: ${{ env.FILE_NAME }}
        run: python EmailToURL.py
